version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/HelloWorldApp/
  - source: /HelloWorld.conf
    destination: /etc/apache2/sites-available/
  - source: /test.txt
    destination: /airflow/test_copy.txt
hooks:
  ApplicationStop:
    - location: applicationStop.sh
      runas: root 
  BeforeInstall:
    - location: beforeInstall.sh
      timeout: 900
  AfterInstall:
    - location: afterInstall.sh
      timeout: 100
  ApplicationStart:
    - location: applicationStart.sh
      runas: root
