version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/HelloWorldApp/
  - source: /test
    destination: /test
hooks:
  BeforeInstall:
    - location: before-install.bat
      timeout: 900
