version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/HelloWorldApp/
  - source: /HelloWorld.conf
    destination: /etc/apache2/sites-available/
  - source: /test.txt
    destination: /airflow
hooks:
  BeforeInstall:
    - location: beforeInstall.sh
      timeout: 900
  ApplicationStart:
    - location: afterInstall.sh
      runas: root
  # AfterInstall:
    # - location: afterInstall.sh
      # timeout: 100
