version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/HelloWorldApp/
  - source: /test.txt
    destination: /airflow
hooks:
  BeforeInstall:
    - location: before-install.bat
      timeout: 900
  AfterInstall:
    - location: after-install.bat
      timeout:100
